# Number of items to show in the TUI.
# Set to -1 to auto-detect based on terminal height.
max_items = -1

# If max_items is set to -1, and the terminal height cannot be detected,
# fallback to this value.
default_max = 10

# Enable debug logging
log = false

[colors]
title = "71"     # jade green (border)
prompt = "79"    # seafoam jade (selected-text accent)
item = "194"     # soft jade-tinted white (text)
selected = "235" # deep jade-black (background highlight)
help = "240"     # muted gray
